# Form implementation generated from reading ui file 'D:\ĐẠI HỌC\ĐẠI HỌC\BẢO MẬT\DETAI_BMHTTT\View\ThietKe\loginDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 409)
        self.b_grad = QtWidgets.QLabel(parent=Dialog)
        self.b_grad.setGeometry(QtCore.QRect(-40, -30, 611, 461))
        self.b_grad.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.b_grad.setText("")
        self.b_grad.setObjectName("b_grad")
        self.b_img = QtWidgets.QLabel(parent=Dialog)
        self.b_img.setGeometry(QtCore.QRect(-260, -180, 891, 721))
        self.b_img.setStyleSheet("background-image: url(D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/637e4098f94e074e846e965d_data-processing-applications-clearpoint.jpeg);")
        self.b_img.setText("")
        self.b_img.setObjectName("b_img")
        self.showPasswordButton = QtWidgets.QPushButton(parent=Dialog)
        self.showPasswordButton.setGeometry(QtCore.QRect(410, 204, 51, 28))
        self.showPasswordButton.setStyleSheet("QPushButton#showPasswordButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#showPasswordButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#showPasswordButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.showPasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/eye-solid.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.showPasswordButton.setIcon(icon)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.cancelButton.setStyleSheet("QPushButton#cancelButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.loginButton = QtWidgets.QPushButton(parent=Dialog)
        self.loginButton.setGeometry(QtCore.QRect(170, 260, 93, 28))
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#loginButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#loginButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 210, 91, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.passwordInput = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordInput.setGeometry(QtCore.QRect(200, 209, 201, 22))
        self.passwordInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 15);")
        self.passwordInput.setInputMask("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 81, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(200, 90, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.usernameInput = QtWidgets.QLineEdit(parent=Dialog)
        self.usernameInput.setGeometry(QtCore.QRect(200, 160, 261, 22))
        self.usernameInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 15);")
        self.usernameInput.setFrame(True)
        self.usernameInput.setObjectName("usernameInput")
        self.b_img.raise_()
        self.b_grad.raise_()
        self.showPasswordButton.raise_()
        self.cancelButton.raise_()
        self.loginButton.raise_()
        self.label_3.raise_()
        self.passwordInput.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.usernameInput.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu:"))
        self.label_2.setText(_translate("Dialog", "Tên tài khoản:"))
        self.label.setText(_translate("Dialog", "Đăng nhập"))
