# Form implementation generated from reading ui file 'D:\ĐẠI HỌC\ĐẠI HỌC\BẢO MẬT\DETAI_BMHTTT\View\ThietKe\signup.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 409)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(200, 110, 261, 22))
        self.usernameInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 15);")
        self.usernameInput.setFrame(True)
        self.usernameInput.setObjectName("usernameInput")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 81, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.passwordInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(200, 159, 201, 22))
        self.passwordInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 15);")
        self.passwordInput.setInputMask("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 160, 91, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.signupButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signupButton.setGeometry(QtCore.QRect(160, 270, 93, 28))
        self.signupButton.setStyleSheet("QPushButton#signupButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#signupButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#signupButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.signupButton.setObjectName("signupButton")
        self.cancelButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(280, 270, 93, 28))
        self.cancelButton.setStyleSheet("QPushButton#cancelButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.showPasswordButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.showPasswordButton.setGeometry(QtCore.QRect(410, 154, 51, 28))
        self.showPasswordButton.setStyleSheet("QPushButton#showPasswordButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#showPasswordButton:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#showPasswordButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.showPasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/eye-solid.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.showPasswordButton.setIcon(icon)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 216, 91, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.passwordInput2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordInput2.setGeometry(QtCore.QRect(200, 215, 201, 22))
        self.passwordInput2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 15);")
        self.passwordInput2.setInputMask("")
        self.passwordInput2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput2.setObjectName("passwordInput2")
        self.showPasswordButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.showPasswordButton2.setGeometry(QtCore.QRect(410, 210, 51, 28))
        self.showPasswordButton2.setStyleSheet("QPushButton#showPasswordButton2{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(25, 54, 82, 255), stop:1 rgba(33, 34, 36, 255));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#showPasswordButton2:hover{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgba(37, 82, 125, 255), stop:1 rgba(57, 60, 64, 255));\n"
"     transition: background 0.5s;\n"
"}\n"
"QPushButton#showPasswordButton2:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"")
        self.showPasswordButton2.setText("")
        self.showPasswordButton2.setIcon(icon)
        self.showPasswordButton2.setObjectName("showPasswordButton2")
        self.b_img = QtWidgets.QLabel(parent=self.centralwidget)
        self.b_img.setGeometry(QtCore.QRect(-260, -180, 891, 721))
        self.b_img.setStyleSheet("background-image: url(D:/ĐẠI HỌC/ĐẠI HỌC/BẢO MẬT/DETAI_BMHTTT/View/Image_and_icons/637e4098f94e074e846e965d_data-processing-applications-clearpoint.jpeg);")
        self.b_img.setText("")
        self.b_img.setObjectName("b_img")
        self.b_grad = QtWidgets.QLabel(parent=self.centralwidget)
        self.b_grad.setGeometry(QtCore.QRect(-40, -30, 611, 461))
        self.b_grad.setStyleSheet("background-color: rgba(0, 0, 0, 0.50);")
        self.b_grad.setText("")
        self.b_grad.setObjectName("b_grad")
        self.b_img.raise_()
        self.b_grad.raise_()
        self.usernameInput.raise_()
        self.label_2.raise_()
        self.passwordInput.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.signupButton.raise_()
        self.cancelButton.raise_()
        self.showPasswordButton.raise_()
        self.label_4.raise_()
        self.passwordInput2.raise_()
        self.showPasswordButton2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Tên tài khoản:"))
        self.label.setText(_translate("MainWindow", "Đăng ký"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu:"))
        self.signupButton.setText(_translate("MainWindow", "Sign up"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label_4.setText(_translate("MainWindow", "Nhập lại mật khẩu:"))
